# Docker Pipeline to build and push an image to ECR

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)' # Use build ID as the tag

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build Docker Image
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # Docker Build step
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
              tags: |
                $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/bookyland-app-repo:$(tag)

          # Docker Push step (Push image to ECR)
          - task: Docker@2
            displayName: Push Docker Image to ECR
            inputs:
              command: push
              repository: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/bookyland-app-repo
              tags: |
                $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/bookyland-app-repo:$(tag)

          # ECR Login (Use AWS CLI)
          - task: ECRPushImage@1
            displayName: Authenticate and Push to ECR
            inputs:
              awsCredentials: 'aws_connection_service'
              regionName: 'us-east-1'
              repositoryName: 'bookyland-app-repo'

