version: 0.2

phases:
  install:
    commands:
      # Install jq for JSON parsing
      - echo Installing jq...
      - apt-get update
      - apt-get install -y jq

  pre_build:
    commands:
      # Show env deploying to
      - echo Deploying into environment $TF_WORKSPACE
      - echo verifying s3 permissions for list and access
      - aws s3 ls s3://devops-tf-state-bookyland

      # Docker Hub Login
      - echo "Logging in Docker Hub..."
      - export DOCKERHUB_TOKEN=$(aws ssm get-parameter --name $SSM_PARAM_DOCKERHUB_TOKEN_NAME --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USER" --password-stdin

      # Log in to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Fetch ssm parameter store
      - echo Getting SSM parameters
      - export TF_VAR_db_password=$(aws ssm get-parameter --name $SSM_PARAM_DB_PASSWORD_NAME --with-decryption --query "Parameter.Value" --output text)

      # Getting AWS temporary credentials
      - echo "Getting AWS temporary credentials..."
      - STS_OUTPUT=$(aws sts get-session-token --output json)
      - export AWS_ACCESS_KEY_ID=$(echo $STS_OUTPUT | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $STS_OUTPUT | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $STS_OUTPUT | jq -r '.Credentials.SessionToken')

  build:
    commands:
      # Build Docker image
      - echo Building Docker image...
      - docker build --compress -t $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION -f ./app/Dockerfile ./app

  post_build:
    commands:
      # Push Docker image to ECR
      - echo "Tagging and pushing Docker image..."
      - docker tag $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:latest
      - docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_URI:latest

      # Initialize and apply Terraform
      - echo Initializing and applying Terraform...
      - cd infra/
      - docker-compose run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN terraform -chdir=deploy/ init
      - docker-compose run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN terraform -chdir=deploy/ workspace select -or-create $workspace
      - docker-compose run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN terraform -chdir=deploy/ apply -auto-approve

      # Done
      - echo "Terraform deployment completed for environment $TF_WORKSPACE."

cache:
  paths:
    - /root/.cache/docker # Docker cache if applicable
