version: 0.2

phases:
  pre_build:
    commands:
      # Show env deploying to
      - echo Deploying into environment $TF_WORKSPACE

      # Docker Hub Login
      - echo "Logging in Docker Hub..."
      - export DOCKERHUB_TOKEN=$(aws ssm get-parameter --name $SSM_PARAM_DOCKERHUB_TOKEN_NAME --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USER" --password-stdin

      # Log in to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      # Fetch ssm parameter store
      - echo Getting SSM parameters
      - export TF_VAR_db_password=$(aws ssm get-parameter --name $SSM_PARAM_DB_PASSWORD_NAME --with-decryption --query "Parameter.Value" --output text)
  
  build:
    commands:
      # Build Docker image
      - echo Building Docker image...
      - docker build --compress -t $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION -f ./app/Dockerfile ./app

  post_build:
    commands:
      # Push Docker image to ECR
      - echo "Tagging and pushing Docker image..."
      - docker tag $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI:latest
      - docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_URI:latest

      # Getting AWS Credentials
      - echo "Getting AWS Credentials"
      - export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
      - export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
      - export AWS_SESSION_TOKEN=$(aws configure get aws_session_token)

      # Initialize and apply Terraform
      - echo Initializing and applying Terraform...
      - cd infra/
      - docker-compose run --rm terraform -chdir=deploy/ init
      - docker-compose run --rm terraform -chdir=deploy/ workspace select -or-create $workspace
      - docker-compose run --rm terraform -chdir=deploy/ apply -auto-approve

      # Done
      - echo "Terraform deployment completed for environment $TF_WORKSPACE."

cache:
  paths:
    - /root/.cache/docker # Docker cache if applicable
