version: 0.2

phases:
  pre_build:
    commands:
      # Install the AWS CLI if not already available
      - echo "Installing dependencies..."
      - pip install awscli --upgrade --user

      # Fetch the secrets from AWS Secrets Manager
      - echo "Fetching RDS credentials from Parameter Store"
      # Parse the secret JSON and export as TF_VAR environment variables
      - export TF_VAR_database_user_password=$(aws ssm get-parameter --name "your-parameter-name" --with-decryption --query "Parameter.Value" --output text)

  build:
    commands:
      - echo "Starting Terraform deployment..."
      - cd infra
      - terraform init
      - terraform apply -auto-approve

artifacts:
  files:
    - "**/*"
  discard-paths: yes

